### ISSUE TITLE
Reversed Horizontal and vertical Resize Icons

### ISSUE THREAD

**Issue by maanasadiyodi** [iamtalhaasghar/windows-mouse-cursor-installer-wizard#2]
dear developer of cursor wizard
i wanted to tell that there is an issue with the file
whenever i put the horizontal and vertical cursors on the respective places and when i click create 
the things go in reverse (horizontal arrow goes to viertical and vertical goes to horizontal). pls fix this 
thx

**Comment by Tutorial-RJ** [comment]
is it fixed?

**Comment by maanasadiyodi** [comment]
Sorry sir its not bout icon its about the reversed text (pls changed to horizontal resize text to vertical resize and vertical resize to Horizontal Resize)
