### ISSUE TITLE
Location Select and Person Select

### ISSUE THREAD

**Issue by dgbogi564** [iamtalhaasghar/windows-mouse-cursor-installer-wizard#3]
You should add the ability to change the location and person select in the wizard.

**Comment by iamtalhaasghar** [comment]
Thank you for taking interest in this repo.
Can u please elaborate the following:

1. Change the location of what?
2. And what do you mean by "person select"?

**Comment by HEYimHeroic** [comment]
there are two mouse cursor types missing from your installation: Location Select and Person Select.

![image](https://user-images.githubusercontent.com/48461034/183307831-187990e5-18ca-4dd7-95b8-81c79aa1edb6.png)

i too would like the ability to customize these.

**Comment by iamtalhaasghar** [comment]
Oh, thanks for response. I didn't knew about these cursors as i haven't used windows OS for a while.
